# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute the IBD Genomic Relationship Matrix
#' @description Computes a IBD relationship matrix from IBD data.
#'
#' @param Markers A numeric matrix of genotype data where rows represent markers
#' and columns represent individuals. Values should range from 0 to ploidy.
#' @param ploidy Integer. it indicates the ploidy level.
#' @return A symmetric numeric matrix of dimensions n x n (where n is the number
#' of individuals) containing the genomic relationship coefficients.
#' @keywords internal
G_ibd <- function(Markers, ploidy) {
    .Call('_SimpleMating_G_ibd', PACKAGE = 'SimpleMating', Markers, ploidy)
}

#' Process Haplotypes for IBD Calculation
#'
#' @title Process Haplotypes for Identity-by-Descent Matrix
#' @description Estimates the identity-by-descent (IBD) relationship matrix from
#' haplotype data using the Allele Matching (AM) method.
#' @param haps_vec A character vector containing haplotype identifiers.
#' The vector should contain ploidy * n_samples elements, where consecutive
#' groups of ploidy elements represent the haplotypes for each sample.
#' @param n_samples Integer. It indicates the number of samples/individuals.
#' @param ploidy Integer. It indicates the ploidy level
#' @return IBD relationship coefficients.
#' @keywords internal
process_haplotypes <- function(haps_vec, n_samples, ploidy) {
    .Call('_SimpleMating_process_haplotypes', PACKAGE = 'SimpleMating', haps_vec, n_samples, ploidy)
}

