# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Process Haplotypes for IBD Calculation
#'
#' @name G_ibd
#' @title Process Haplotypes for Identity-by-Descent Matrix
#' @description Computes an identity-by-descent (IBD) relationship matrix from
#' haplotype data using the Allele Matching (AM) method. Counts matching
#' haplotypes between individuals and scales by ploidy.
#' @param haps_vec A character vector containing haplotype identifiers.
#' The vector should contain ploidy * n_samples elements, where consecutive
#' groups of ploidy elements represent the haplotypes for each sample.
#' @param n_samples An integer indicating the number of samples/individuals.
#' @param ploidy An integer indicating the ploidy level of the organism
#' (e.g., 2 for diploid, 4 for tetraploid).
#' @return A symmetric numeric matrix of dimensions n_samples x n_samples
#' containing the IBD relationship coefficients based on haplotype matching.
#' @keywords internal
G_ibd <- function(haps_vec, n_samples, ploidy) {
    .Call(`_SimpleMating_G_ibd`, haps_vec, n_samples, ploidy)
}

getTGVcpp <- function(markers, effA, effD, parent1_idx, parent2_idx, ploidy) {
    .Call(`_SimpleMating_getTGVcpp`, markers, effA, effD, parent1_idx, parent2_idx, ploidy)
}

computeTGV_single_cpp <- function(markers, effA, effD, parent1_idx, parent2_idx, ploidy) {
    .Call(`_SimpleMating_computeTGV_single_cpp`, markers, effA, effD, parent1_idx, parent2_idx, ploidy)
}

meltK_TGV_cpp <- function(X, namesK) {
    .Call(`_SimpleMating_meltK_TGV_cpp`, X, namesK)
}

imputeMarkersCpp <- function(markers) {
    .Call(`_SimpleMating_imputeMarkersCpp`, markers)
}

